/**
 * NotebookTab - Personal Study Journal
 *
 * Consolidates all personal tracking features:
 * - Questions (Kushyot): Track questions while learning
 * - Insights (Chiddushim): Record novel insights
 * - Progress: Track understanding levels and mastery
 * - Today: Today's learning summary and streak + Study Mode selector
 *
 * This is your personal "machberet" (notebook) for Torah study.
 */

import React, { useState, useCallback, lazy, Suspense } from 'react';
import PropTypes from 'prop-types';
import { useStudyMode } from '../../context/StudyModeContext';
import useMastery from '../../hooks/useMastery';
import './NotebookTab.css';

// PRO SCHOLAR V6: Lazy-loaded analytics panel
const StudyInsightsPanel = lazy(() => import('../study/StudyInsightsPanel'));

// Loading fallback
const AnalyticsFallback = () => (
  <div className="analytics-loading">
    <div className="skeleton-bar" style={{ width: '80%', height: '24px', marginBottom: '16px' }} />
    <div className="skeleton-bar" style={{ width: '60%', height: '18px', marginBottom: '12px' }} />
    <div className="skeleton-bar" style={{ width: '70%', height: '18px' }} />
  </div>
);

// =============================================================================
// Sub-tab configurations
// =============================================================================
const SUB_TABS = [
  { id: 'questions', label: 'קושיות', sublabel: 'Questions', icon: '❓', description: 'Track your questions' },
  { id: 'insights', label: 'חידושים', sublabel: 'Insights', icon: '✨', description: 'Record novel insights' },
  { id: 'progress', label: 'התקדמות', sublabel: 'Progress', icon: '📈', description: 'Track mastery' },
  { id: 'analytics', label: 'ניתוח', sublabel: 'Analytics', icon: '📊', description: 'Study analytics' },
  { id: 'chazara', label: 'חזרה', sublabel: 'Chazara', icon: '🔄', description: 'Spaced repetition review' },
  { id: 'today', label: 'היום', sublabel: 'Today', icon: '📅', description: "Today's summary" }
];

// Sections déplacées dans ./NotebookTab/sections/ (recette tests de rendu d'abord).
import { QuestionsSection } from './NotebookTab/sections/QuestionsSection';

import { InsightsSection } from './NotebookTab/sections/InsightsSection';

import { ProgressSection } from './NotebookTab/sections/ProgressSection';

import { ChazaraSection } from './NotebookTab/sections/ChazaraSection';

// TodaySection (avec FeatureIndicator) déplacée dans ./NotebookTab/sections/.
import { TodaySection } from './NotebookTab/sections/TodaySection';



// =============================================================================
// Main NotebookTab Component
// =============================================================================
// =============================================================================
// Export to Markdown
// =============================================================================
const exportToMarkdown = (kushyot, chiddushim) => {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  let markdown = `# Torah Study Notes\n`;
  markdown += `*Exported: ${date}*\n\n`;

  // Export Questions
  if (kushyot && kushyot.length > 0) {
    markdown += `## ❓ Questions (קושיות)\n\n`;
    kushyot.forEach((k, idx) => {
      const status = k.status === 'resolved' ? '✅' : k.status === 'deferred' ? '⏸️' : '❓';
      const ref = k.context ? `${k.context.book} ${k.context.chapter}:${k.context.verse}` : '';
      markdown += `### ${idx + 1}. ${status} ${k.question}\n`;
      if (ref) markdown += `*Reference: ${ref}*\n\n`;
      if (k.terutz) markdown += `**Answer:** ${k.terutz}\n\n`;
      markdown += `---\n\n`;
    });
  }

  // Export Insights
  if (chiddushim && chiddushim.length > 0) {
    markdown += `## ✨ Insights (חידושים)\n\n`;
    chiddushim.forEach((c, idx) => {
      const ref = c.context ? `${c.context.book} ${c.context.chapter}` : '';
      markdown += `### ${idx + 1}. ${c.title || 'Insight'}\n`;
      if (ref) markdown += `*${ref}*\n\n`;
      markdown += `${c.content}\n\n`;
      if (c.tags && c.tags.length > 0) {
        markdown += `**Tags:** ${c.tags.join(', ')}\n\n`;
      }
      markdown += `---\n\n`;
    });
  }

  markdown += `\n---\n*Generated by Sefarim Reader*`;

  return markdown;
};

const downloadMarkdown = (content, filename) => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const NotebookTab = ({
  selectedBook,
  selectedChapter,
  selectedVerse,
  totalVerses,
  onNavigateToVerse
}) => {
  const [activeSubTab, setActiveSubTab] = useState('questions');
  const [isTransitioning, setIsTransitioning] = useState(false);

  // Get data from StudyModeContext
  const { kushyot = [], chiddushim = [] } = useStudyMode();

  // Get due items count for badge
  const { getDueForReview } = useMastery();
  const dueCount = getDueForReview().filter(i => i.type === 'verse').length;

  const currentContext = {
    book: selectedBook,
    chapter: selectedChapter,
    verse: selectedVerse?.verse
  };

  const handleSubTabSwitch = useCallback((newTab) => {
    if (newTab === activeSubTab) return;
    setIsTransitioning(true);
    setTimeout(() => {
      setActiveSubTab(newTab);
      setIsTransitioning(false);
    }, 150);
  }, [activeSubTab]);

  const handleExport = useCallback(() => {
    const markdown = exportToMarkdown(kushyot, chiddushim);
    const date = new Date().toISOString().split('T')[0];
    downloadMarkdown(markdown, `torah-notes-${date}.md`);
  }, [kushyot, chiddushim]);

  const totalNotes = (kushyot?.length || 0) + (chiddushim?.length || 0);

  return (
    <div className="notebook-tab">
      {/* Header with export */}
      <div className="notebook-header">
        <span className="notebook-title">📓 מחברת</span>
        {totalNotes > 0 && (
          <button
            className="export-btn"
            onClick={handleExport}
            title="Export notes to Markdown"
          >
            📥 Export ({totalNotes})
          </button>
        )}
      </div>

      {/* Sub-tab navigation */}
      <div className="notebook-sub-tabs">
        {SUB_TABS.map(tab => (
          <button
            key={tab.id}
            className={`sub-tab-btn ${activeSubTab === tab.id ? 'active' : ''}`}
            onClick={() => handleSubTabSwitch(tab.id)}
            disabled={isTransitioning}
          >
            <span className="sub-tab-icon">{tab.icon}</span>
            <span className="sub-tab-label">{tab.label}</span>
            <span className="sub-tab-sublabel">{tab.sublabel}</span>
            {tab.id === 'chazara' && dueCount > 0 && (
              <span className="sub-tab-badge">{dueCount}</span>
            )}
          </button>
        ))}
      </div>

      {/* Content area */}
      <div className={`notebook-content ${isTransitioning ? 'transitioning' : ''}`}>
        {activeSubTab === 'questions' && (
          <QuestionsSection currentContext={currentContext} />
        )}

        {activeSubTab === 'insights' && (
          <InsightsSection
            currentBook={selectedBook}
            currentChapter={selectedChapter}
          />
        )}

        {activeSubTab === 'progress' && (
          <ProgressSection
            currentBook={selectedBook}
            currentChapter={selectedChapter}
            currentVerse={selectedVerse?.verse}
            totalVerses={totalVerses}
            onNavigateToVerse={onNavigateToVerse}
          />
        )}

        {activeSubTab === 'analytics' && (
          <Suspense fallback={<AnalyticsFallback />}>
            <StudyInsightsPanel
              currentBook={selectedBook}
              currentChapter={selectedChapter}
            />
          </Suspense>
        )}

        {activeSubTab === 'chazara' && (
          <ChazaraSection onNavigateToVerse={onNavigateToVerse} />
        )}

        {activeSubTab === 'today' && (
          <TodaySection
            currentBook={selectedBook}
            currentChapter={selectedChapter}
          />
        )}
      </div>
    </div>
  );
};

NotebookTab.propTypes = {
  selectedBook: PropTypes.string,
  selectedChapter: PropTypes.number,
  selectedVerse: PropTypes.object,
  totalVerses: PropTypes.number,
  onNavigateToVerse: PropTypes.func
};

export default NotebookTab;
